//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountriesDBTransfer.DAL.MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Neighborhood
    {
        public int NeighborhoodID { get; set; }
        public int AreaID { get; set; }
        public string NeighborhoodName { get; set; }
        public string ZipCode { get; set; }
    
        public virtual Area Area { get; set; }
    }
}
